# config context path to "/" by setting an empty string
server:
  port: 5454
  contextPath:

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

  datasource:
    url: jdbc:postgresql://${POSTGRES_IP}:${POSTGRES_PORT}/und
    driver-class-name: org.postgresql.Driver
    username: postgres
    password:  postgres
    tomcat:
      initial-size: 10
      max-wait: 10000
      max-active: 50
      test-on-borrow: true


  data:
    mongodb:
      uri: mongodb://${MONGO_IP}:${MONGO_PORT}/eventdb
      database: eventdb
      # username: eventuser
      # password: password
      host: ${MONGO_IP}
      port: ${MONGO_PORT}
      #27017

security:
  header:
    token: Authorization
    username: UserName
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

kafka:
  ip: ${KAFKA_IP}
  port: ${KAFKA_PORT}
  #6667
  topic:
    event: Event-API
    userevent: User-Event-API
    eventUser: event-user

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_IP}
          defaultBrokerPort: ${KAFKA_PORT}
          zkNodes: ${KAFKA_IP}
          defaultZkPort: 2181
          offsetUpdateCount: 1
          #replicationFactor: 2
          #minPartitionCount: true
          minPartitionCount: 2
        bindings:
          event:
            group: eventprocess
            destination: eventprocess
            consumer:
              #startOffset: earliest
              group: eventprocess
          eventUser:
            group: eventUserprocess
            destination: eventUserprocess
            consumer:
              #startOffset: earliest
              group: eventUserprocess
          processedEventUserProfile:
              group: eventUserprocessEvents
              destination: eventUserprocessEvents
              consumer:
                #startOffset: earliest
                group: eventUserprocessEvents
#logging:
#  level:
#    org.springframework:
#      security: DEBUG
eureka:
  instance:
    prefer-ip-address: true
    health-check-url-path: /application/health
  client:
    register-with-eureka: true
    fetch-registry: true
    region: desktop
    service-url:
      defaultZone: http://${EUREKA_IP}:${EUREKA_PORT}/eureka


