# config context path to "/" by setting an empty string
server:
  port: 9595
  contextPath:

# JACKSON
spring:
  application:
    name: auth-service
  thymeleaf:
    cache: false
  jackson:
    serialization:
      INDENT_OUTPUT: true

  datasource:
    url: jdbc:postgresql://${POSTGRES_IP}:${POSTGRES_PORT}/und
    driver-class-name: org.postgresql.Driver
    username: postgres
    password:  postgres
    tomcat:
      initial-size: 10
      max-wait: 10000
      max-active: 50
      test-on-borrow: true

  redis:
    host: ${REDIS_IP}
    port: ${REDIS_PORT}

security:
  header:
    token: Authorization
    username: UserName
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      userdetail: userdetail
      validate: auth/validate

eureka:
  instance:
    prefer-ip-address: true
    health-check-url-path: /application/health
  client:
    register-with-eureka: true
    fetch-registry: true
    region: desktop
    service-url:
      defaultZone: http://${EUREKA_IP}:${EUREKA_PORT}/eureka
