server:
  port: 8080

spring:
  application:
    name: gateway-service  

zuul:
  routes:
    auth-service:
      path: /auth/**
      sensitiveHeaders:
    client-panel:
      path: /client/**
      sensitiveHeaders: