# config context path to "/" by setting an empty string
server:
  port: 6363
  contextPath:

# JACKSON
spring:
  application:
    name: und-scheduler
  jackson:
    serialization:
      write-dates-as-timestamps: false
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://${POSTGRES_IP}:${POSTGRES_PORT}/recurrence
    driver-class-name: org.postgresql.Driver
    username: postgres
    password:  postgres
    tomcat:
      initial-size: 10
      max-wait: 10000
      max-active: 50
      test-on-borrow: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.0.109
          defaultBrokerPort: ${KAFKA_PORT}
          zkNodes: 192.168.0.109
          defaultZkPort: 2181
        bindings:
          scheduleJob:
            group: scheduleJobGroup
            destination: scheduleJob
          campaignTrigger:
            group: campaignTriggerGroup
            destination: campaignTrigger
            consumer:
              group: campaignTriggerGroup
      binders:
          scheduleJob:
            group: scheduleJobGroup
            destination: scheduleJob
  kafka:
    admin:
      properties:
        client.id: scheduler

security:
  header:
    token: authorization
    username: UserName
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

eureka:
  instance:
    prefer-ip-address: true
    health-check-url-path: /application/health
  client:
    register-with-eureka: true
    fetch-registry: true
    region: desktop
    service-url:
      defaultZone: http://${EUREKA_IP}:${EUREKA_PORT}/eureka
