# config context path to "/" by setting an empty string
server:
  port: 5454
  contextPath:

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

  datasource:
    url: jdbc:postgresql://${POSTGRES_IP}:${POSTGRES_PORT}/kamal
    driver-class-name: org.postgresql.Driver
    username: postgres
    password:  postgres
    tomcat:
      initial-size: 10
      max-wait: 10000
      max-active: 50
      test-on-borrow: true


  data:
    mongodb:
      uri: mongodb://${MONGO_IP}:${MONGO_PORT}/eventdb


security:
  header:
    token: Authorization
    username: UserName
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh



spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_IP}
          defaultBrokerPort: ${KAFKA_PORT}
          zkNodes: ${KAFKA_IP}
          defaultZkPort: 2181
          offsetUpdateCount: 1
          #replicationFactor: 2
          #minPartitionCount: true
          minPartitionCount: 2
        bindings:
          rruleInput:
            group: rruleInput
            destination: rruleInput
            consumer:
              #startOffset: earliest
              group: rruleInput

#logging:
#  level:
#    org.springframework:
#      security: DEBUG
eureka:
  instance:
    prefer-ip-address: true
    health-check-url-path: /application/health
  client:
    register-with-eureka: true
    fetch-registry: true
    region: desktop
    service-url:
      defaultZone: http://${EUREKA_IP}:${EUREKA_PORT}/eureka


