# config context path to "/" by setting an empty string
server:
  port: 7474


# JACKSON
spring:
  application:
    name: emailsendservice
  thymeleaf:
    cache: false
  jackson:
    serialization:
      INDENT_OUTPUT: true
  redis:
    host: ${REDIS_IP}
    port: ${REDIS_PORT}
  cache:
    redis:
      use-key-prefix: true
  cloud:
      stream:
        kafka:
          binder:
            brokers: ${KAFKA_IP}
            defaultBrokerPort: ${KAFKA_PORT}
            zkNodes: ${KAFKA_IP}
            defaultZkPort: 2181
            configuration:
              enable:
                auto:
                  commit: true
              auto:
                offset:
                  reset: earliest
                commit:
                  interval:
                    ms: 10000
          bindings:
            emailEventSend:
              producer:
                configuration:
                  client:
                    id: 1
              group: emailEventGroup
              destination: emailEvent
            emailEventReceive:
              consumer:
                configuration:
                  client:
                    id: 1
                  group:
                    id: emailEventReceive
              group: emailEventReceive
              destination: emailEvent
            smsEventSend:
              producer:
                configuration:
                  client:
                    id: 2
              group: smsEventGroup
              destination: smsEvent
            smsEventReceive:
              consumer:
                configuration:
                  client:
                    id: 2
                  group:
                    id: smsEventReceive
              group: smsEventReceive
              destination: smsEvent
            clientEmailReceive:
              consumer:
                configuration:
                  client:
                    id: 3
                  group:
                    id: clientEmailReceiveGroup
              group: clientEmailReceiveGroup
              destination: clientEmail
            clickTrackEventReceive:
              consumer:
                configuration:
                  client:
                    id: 4
                  group:
                    id: clickTrackEventGroup
              group: clickTrackEventGroup
              destination: clickTrackEvent
            EmailUpdateReceive:
              consumer:
                configuration:
                  client:
                    id: 5
                  group:
                    id: EmailUpdateReceiveGroup
              group: EmailUpdateReceiveGroup
              destination: EmailUpdate
            campaignTriggerReceive:
              consumer:
                configuration:
                  client:
                    id: 6
                  group:
                    id: campaignTriggerReceive
              group: campaignTriggerReceive
              destination: campaignTrigger
            fcmEventSend:
              producer:
                configuration:
                  client:
                    id: 3
              group: fcmMessageGroup
              destination: fcmMessage
            fcmEventReceive:
              consumer:
                configuration:
                  client:
                    id: 7
                  group:
                    id: fcmMessageReceiveGroup
              group: fcmMessageReceiveGroup
              destination: fcmMessage
            fcmFailureEventSend:
              producer:
                configuration:
                  client:
                    id: 4
              group: fcmFailureEventGroup
              destination: fcmEventFailure
            emailFailureEventSend:
              producer:
                configuration:
                  client:
                    id: 5
              group: emailFailureEventGroup
              destination: emailFailureEvent
            VerificationEmailReceive:
              consumer:
                configuration:
                  client:
                    id: 8
                  group:
                    id: verificationEmailReceive
              group: verificationEmailReceive
              destination: verificationEmail
            inLiveSegment:
              consumer:
                configuration:
                  client:
                    id: 9
                  group:
                    id: processLiveUserReceiveGroup
              group: processLiveUserReceiveGroup
              destination: processliveuser
            inTestCampaign:
              consumer:
                configuration:
                  client:
                    id: 10
                  group:
                    id: testCampaignReceiveGroup
              group: testCampaignReceiveGroup
              destination: testCampaign
            abCampaignTriggerReceive:
              consumer:
                configuration:
                  client:
                    id: 11
                  group:
                    id: abCampaignTriggerReceiveGroup
            receiveManualTriggerCampaign:
              consumer:
                configuration:
                  client:
                    id: 12
                  group:
                    id: manualCampaignTriggerReceiveGroup
              group: manualCampaignTriggerReceiveGroup
              destination: manualCampaign
            scheduleJobSend:
              group: scheduleJobGroup
              destination: scheduleJob
            clientEmailSend:
              destination: clientEmail
            outTestEmail:
              destination: testEmail
            outTestSms:
              destination: testSms
            outTestFcm:
              destination: testFcm
            outEmailLiveCampaign:
              destination: emailLiveCampaign
            outSmsLiveCampaign:
              destination: smsLiveCampaign
            outFcmLiveCampaign:
              destination: fcmLiveCampaign
            inTestEmail:
              consumer:
                configuration:
                  client:
                    id: 13
                  group:
                    id: testEmailGroup
              destination: testEmail
            inTestSms:
              consumer:
                configuration:
                  client:
                    id: 14
                  group:
                    id: testSmsGroup
              destination: testSms
            inTestFcm:
              consumer:
                configuration:
                  client:
                    id: 14
                  group:
                    id: testFcmGroup
              destination: testFcm
            inEmailLiveCampaign:
              consumer:
                configuration:
                  client:
                    id: 15
                  group:
                    id: liveEmailGroup
              destination: emailLiveCampaign
            inSmsLiveCampaign:
              consumer:
                configuration:
                  client:
                    id: 16
                  group:
                    id: liveSmsGroup
              destination: smsLiveCampaign
            inFcmLiveCampaign:
              consumer:
                configuration:
                  client:
                    id: 17
                  group:
                    id: liveFcmGroup
              destination: fcmLiveCampaign
        bindings:
          emailEventSend:
            group: emailEventGroup
            destination: emailEvent
          emailEventReceive:
            group: emailEventReceive
            destination: emailEvent
          smsEventSend:
            group: smsEventGroup
            destination: smsEvent
          smsEventReceive:
            group: smsEventReceive
            destination: smsEvent
          clientEmailReceive:
            group: clientEmailReceiveGroup
            destination: clientEmail
          clickTrackEventReceive:
            group: clickTrackEventGroup
            destination: clickTrackEvent
          EmailUpdateReceive:
            group: EmailUpdateReceiveGroup
            destination: EmailUpdate
          campaignTriggerReceive:
            group: campaignTriggerReceive
            destination: campaignTrigger
          fcmEventSend:
            group: fcmMessageGroup
            destination: fcmMessage
          fcmEventReceive:
            group: fcmMessageReceiveGroup
            destination: fcmMessage
          fcmFailureEventSend:
            group: fcmFailureEventGroup
            destination: fcmEventFailure
          emailFailureEventSend:
            group: emailFailureEventGroup
            destination: emailFailureEvent
          VerificationEmailReceive:
            group: verificationEmailReceive
            destination: verificationEmail
          inLiveSegment:
            destination: processliveuser
          inTestCampaign:
            destination: testCampaign
          abCampaignTriggerReceive:
            destination: abCampaignTrigger
          receiveManualTriggerCampaign:
            destination: manualCampaign
          scheduleJobSend:
            destination: scheduleJob
          clientEmailSend:
            destination: clientEmail
          outTestEmail:
            destination: testEmail
          outTestSms:
            destination: testSms
          outTestFcm:
            destination: testFcm
          outEmailLiveCampaign:
            destination: emailLiveCampaign
          outSmsLiveCampaign:
            destination: smsLiveCampaign
          outFcmLiveCampaign:
            destination: fcmLiveCampaign
          inTestEmail:
            destination: testEmail
          inTestSms:
            destination: testSms
          inTestFcm:
            destination: testFcm
          inEmailLiveCampaign:
            destination: emailLiveCampaign
          inSmsLiveCampaign:
            destination: smsLiveCampaign
          inFcmLiveCampaign:
            destination: fcmLiveCampaign
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

  datasource:
    url: jdbc:postgresql://${POSTGRES_IP}:${POSTGRES_PORT}/und
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    tomcat:
      initial-size: 10
      max-wait: 10000
      max-active: 50
      test-on-borrow: true
  data:
    mongodb:
      database: eventdb
      host: ${MONGO_IP}
      port: ${MONGO_PORT}

  kafka:
    bootstrap-servers: ${KAFKA_IP}:${KAFKA_PORT}

security:
  header:
    token: authorization
    username: UserName
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

eureka:
  instance:
    prefer-ip-address: true
    health-check-url-path: /email-service/health
  client:
    register-with-eureka: true
    fetch-registry: true
    region: desktop
    service-url:
      defaultZone: http://${EUREKA_IP}:${EUREKA_PORT}/eureka

logging:
  level:
    org:
      springframework: info
      apache: info
      hibernate: info
    com:
      und: info
  file: ${HOME}/log/und-emailsendservice.log

encryption-decryption:
  key:
    default: DaO1TXt5B0R92Yys
    unsubscribe: TaO5T01R9BXt2yYS

und:
  system:
    user:
      token: jasdghajskdhg
    email:
      setting:
        id: 1
    from:
      address: admin@userndot.com
  url:
    event: https://userndot.com/event
  auth-url: https://userndot.com/auth
  from-email: admin@userndot.com
  lambda:
    sms:
      secretKey: tEA3hwNdgerwF4oiVIscjtvEbPIJvwePxrNCAdhv
      accessKey: AKIAIEEV7Q6MG5DLL52Q
      region : ap-south-1
      functionName: exotel