# config context path to "/" by setting an empty string
server:
  port: 7474

# JACKSON
spring:
  application:
    name: emailsendservice
  thymeleaf:
    cache: false
  jackson:
    serialization:
      INDENT_OUTPUT: true
  cloud:
      stream:
        kafka:
          binder:
            brokers: ${KAFKA_IP}
            defaultBrokerPort: ${KAFKA_PORT}
            zkNodes: ${KAFKA_IP}
            defaultZkPort: 2181
        bindings:
          emailEvent:
            group: emailEventGroup
            destination: emailEvent
          EmailReadEvent:
            group: eEmailReadEventGroup
            destination: EmailReadEvent
          clickTrackEvent:
            group: clickTrackEventGroup
            destination: clickTrackEvent
      binders:
          emailEvent:
            group: emailEventGroup
            destination: emailEvent
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    url: jdbc:postgresql://${POSTGRES_IP}:${POSTGRES_PORT}/und
    driver-class-name: org.postgresql.Driver
    username: postgres
    password:  postgres
    tomcat:
      initial-size: 10
      max-wait: 10000
      max-active: 50
      test-on-borrow: true
  data:
    mongodb:
      database: eventdb
      host: ${MONGO_IP}
      port: ${MONGO_PORT}

  kafka:
    admin:
      properties:
        client.id: emailsendservice
security:
  header:
    token: authorization
    username: UserName
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

eureka:
  instance:
    prefer-ip-address: true
    health-check-url-path: /application/health
  client:
    register-with-eureka: true
    fetch-registry: true
    region: desktop
    service-url:
      defaultZone: http://${EUREKA_IP}:${EUREKA_PORT}/eureka


logging:
  level:
    org:
      springframework: info
      apache: info
      hibernate: info
    com:
      und: info
  file: log/und-emailsendservice.log


encryption-decryption:
  key:
    default: DaO1TXt5B0R92Yys
    unsubscribe: TaO5T01R9BXt2yYS